local builtin = require('telescope.builtin')
vim.g.mapleader = ' '
vim.keymap.set('n', '<leader>e', vim.cmd.Ex, { desc = 'File [E]xplorer' })
vim.keymap.set('n', '<leader>w', vim.cmd.w, { desc = '[W]rite' })
vim.keymap.set('i', 'kj', '<esc>')
vim.keymap.set('n', '<leader><leader>', vim.cmd.so, { desc = '[S]ource' })
vim.keymap.set('n', '<leader>sf', builtin.find_files, { desc = '[S]earch [F]iles in current dir' })
vim.keymap.set('n', '<C-g>', builtin.git_files, { desc = 'Search current [G]it dir' })
vim.keymap.set('n', '<leader>sg', function()
	builtin.grep_string({ search = vim.fn.input('Grep > ') })
end, { desc = '[S]earch [G]rep' })
vim.keymap.set('n', '<leader>q', vim.cmd.q, { desc = '[Q]uit' })
vim.keymap.set('n', '<leader>fq', ':q!<CR>', { desc = '[F]orce [Q]uit' })
vim.keymap.set('n', 'gw', '<C-w>', { desc = '[G]et [W]indow' })
-- Replaces all occurences of the word under the cursor; requires confirmation
vim.keymap.set('n', '<leader>/r', [[:%s/<C-r><C-w>//gc<Left><Left><Left>]], { desc = 'Find[/R]eplace' })
